version: "3.6"

x-template: &template
  image: irixjp/pai-app-base:latest
  privileged: true
  command: /sbin/init
  restart: unless-stopped
  environment:
    TZ: Asia/Tokyo

services:
  jupyter:
    image: irixjp/pai-jupyter:latest
    container_name: console
    hostname: console
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8888"
    environment:
      JPL_PASSWORD: password
      TOWER_HOST: "http://192.168.77.13:8052/"
      TOWER_VERIFY_SSL: "False"
      TZ: Asia/Tokyo
    labels:
      infra.description: "console"
      infra.group: "infra"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.10

  gitlab:
    image: irixjp/pai-gitlab-ce:12.10.11-ce.0
    container_name: gitlab
    hostname: gitlab
    restart: unless-stopped
    volumes:
      - "./files/gitlab.rb:/etc/gitlab/gitlab.rb"
    ports:
      - "8081:80"
    environment:
      TZ: Asia/Tokyo
    labels:
      infra.description: "gitlab"
      infra.group: "infra"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.11

  gitlab-runner:
    image: irixjp/pai-gitlab-runner:v12.9.1
    container_name: gitlab-runner
    hostname: gitlab-runner
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: Asia/Tokyo
    labels:
      infra.description: "gitlab-runner"
      infra.group: "infra"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.12

  web:
    image: irixjp/pai-awx:12.0.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "8082:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./files/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./files/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./files/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./files/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./files/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy:
      TZ: Asia/Tokyo
    labels:
      infra.description: "awx_web"
      infra.group: "infra"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.13

  task:
    image: irixjp/pai-awx:12.0.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./files/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./files/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./files/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./files/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'
      TZ: Asia/Tokyo
    labels:
      infra.description: "awx_task"
      infra.group: "infra"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.14

  redis:
    image: irixjp/pai-redis:buster
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./files/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "./files/redis_socket:/var/run/redis/:rw"
    environment:
      TZ: Asia/Tokyo
    labels:
      infra.description: "awx_redis"
      infra.group: "infra"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.15

  postgres:
    image: irixjp/pai-postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy:
      TZ: Asia/Tokyo
    labels:
      infra.description: "awx_postgres"
      infra.group: "infra"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.16

  test_lb:
    <<: *template
    container_name: test-lb
    hostname: test-lb
    ports:
      - "8180:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.100

  test_web1:
    <<: *template
    container_name: test-web1
    hostname: test-web1
    ports:
      - "8181:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.111

  test_web2:
    <<: *template
    container_name: test-web2
    hostname: test-web2
    ports:
      - "8182:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.112

  test_db:
    <<: *template
    container_name: test-db
    hostname: test-db
    ports:
      - "8183:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.123

  prod_lb:
    <<: *template
    container_name: prod-lb
    hostname: prod-lb
    ports:
      - "8190:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.200

  prod_web1:
    <<: *template
    container_name: prod-web1
    hostname: prod-web1
    ports:
      - "8191:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.211

  prod_web2:
    <<: *template
    container_name: prod-web2
    hostname: prod-web2
    ports:
      - "8192:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.212

  prod_db:
    <<: *template
    container_name: prod-db
    hostname: prod-db
    ports:
      - "8193:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.223

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:

networks:
  infraci_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.77.0/24
