version: "3.6"

services:
  jupyter:
    image: irixjp/pai-jupyter:latest
    container_name: console
    hostname: console
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8888"
    environment:
      JPL_PASSWORD: password
      TOWER_HOST: "http://192.168.77.13:8052/"
      TOWER_VERIFY_SSL: "False"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.10

  gitlab:
    image: irixjp/pai-gitlab-ce:12.10.11-ce.0
    container_name: gitlab
    hostname: gitlab
    restart: unless-stopped
    volumes:
      - "./files/gitlab.rb:/etc/gitlab/gitlab.rb"
    ports:
      - "8081:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.11

  gitlab-runner:
    image: irixjp/pai-gitlab-runner:v12.9.1
    container_name: gitlab-runner
    hostname: gitlab-runner
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.12

  web:
    image: irixjp/pai-awx:12.0.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "8082:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./files/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./files/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./files/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./files/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./files/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.13

  task:
    image: irixjp/pai-awx:12.0.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "./files/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./files/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./files/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./files/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.14

  redis:
    image: irixjp/pai-redis:buster
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./files/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "./files/redis_socket:/var/run/redis/:rw"
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.15

  postgres:
    image: irixjp/pai-postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 
    networks:
      infraci_nw:
        ipv4_address: 192.168.77.16

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:

networks:
  infraci_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.77.0/24
